# yaml-language-server: $schema=https://raw.githubusercontent.com/reqstool/reqstool-client/main/src/reqstool/resources/schemas/v1/requirements.schema.json
metadata:
  urn: atunko-tui
  variant: microservice
  title: Atunko TUI Module Requirements

imports:
  local:
    - path: ../../../docs/reqstool

filters:
  atunko:
    requirement_ids:
      includes:
        - TUI_0001
        - TUI_0001.1
        - TUI_0001.2
        - TUI_0001.3
        - TUI_0001.4
        - TUI_0001.5
        - TUI_0001.6
        - TUI_0001.7
        - TUI_0001.8
        - TUI_0001.9
        - TUI_0001.10
        - TUI_0001.11
        - TUI_0001.12
        - TUI_0001.13
        - TUI_0001.14
        - TUI_0001.15
        - TUI_0001.16
