# yaml-language-server: $schema=https://raw.githubusercontent.com/reqstool/reqstool-client/main/src/reqstool/resources/schemas/v1/requirements.schema.json
metadata:
  urn: atunko-app
  variant: microservice
  title: Atunko App Module Requirements

imports:
  local:
    - path: ../../../docs/reqstool

filters:
  atunko:
    requirement_ids:
      includes:
        - CLI_0001
        - CLI_0001.1
        - CLI_0001.2
        - CLI_0001.3
        - CLI_0001.4
        - CLI_0001.5
        - CLI_0001.6
        - CLI_0001.7
        - CLI_0001.8
        - CLI_0001.9
        - CLI_0001.10
        - CLI_0001.11
        - CLI_0001.12
        - CLI_0001.13
        - CLI_0001.14
        - CLI_0001.15
        - CLI_0002
        - CLI_0002.1
        - CLI_0002.2
        - CLI_0002.3
        - CLI_0002.4
        - CLI_0003
        - CLI_0004
        - CLI_0004.1
        - CLI_0004.2
        - CLI_0004.3
        - CLI_0004.4
        - CLI_0004.5
